networks:
  app-network:
    driver: bridge

volumes:
  keycloak-db-shop-data:
  hydra-data:

services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka_shop
    networks: [ app-network ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shop_api
    networks: [ app-network ]
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - KAFKA_GROUP_ID=shop-backend-dashboard
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      kafka:
        condition: service_healthy

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shop_worker
    networks: [ app-network ]
    command: ["node", "kafka/consumer.js"]
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      kafka:
        condition: service_healthy

  frontend:
    build:
      context: ./frontEnd
    networks: [ app-network ]
    container_name: shop_frontend
    ports:
      - "3001:3001"

  keycloak-db-shop:
    image: postgres:15-alpine
    container_name: keycloak-db-shop
    networks: [ app-network ]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - keycloak-db-shop-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 3s
      retries: 5

  keycloak-shop:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak_shop
    depends_on:
      keycloak-db-shop: { condition: service_healthy }
    networks: [ app-network ]
    ports:
      - "8081:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_LOG_LEVEL: INFO
    volumes:
      - ./keycloak-shop:/opt/keycloak/data/import:ro
    command:
      - start-dev
      - --import-realm

  hydra-postgres:
    image: postgres:15
    networks: [ app-network ]
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    ports:
      - "5433:5432"
    volumes:
      - hydra-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hydra" ]
      interval: 5s
      timeout: 5s
      retries: 5

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    networks: [ app-network ]
    environment:
      - DSN=postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes
    depends_on:
      - hydra-postgres
    restart: on-failure

  hydra:
    image: oryd/hydra:v2.2.0
    networks: [ app-network ]
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully
      hydra-postgres:
        condition: service_healthy
    ports:
      - "4444:4444"
      - "4445:4445"
      - "5555:5555"
    command: serve all --dev
    environment:
      - DSN=postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://localhost:3001/login-hydra
      - URLS_CONSENT=http://localhost:3000/hydra/consent
      - URLS_LOGOUT=http://localhost:3000/hydra/logout
      - SECRETS_SYSTEM=votre_secret_tres_long_et_securise_pour_hydra
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hydra-init:
    image: oryd/hydra:v2.2.0
    container_name: hydra_client_init
    networks: [ app-network ]
    depends_on:
      - hydra
    restart: "no"
    entrypoint: /bin/sh
    command: >
      -c "
      echo '⏳ Attente du démarrage de Hydra Admin...';
      while ! wget -q -O - http://hydra:4445/health/ready >/dev/null 2>&1; do sleep 1; done;
      echo '✅ Hydra est prêt ! Création du client via l API...';
      wget --header='Content-Type: application/json' --post-data='{\"client_id\":\"my-react-client\",\"client_name\":\"Comparaison Client\",\"client_secret\":\"my-secret-password\",\"grant_types\":[\"authorization_code\",\"refresh_token\"],\"response_types\":[\"code\",\"id_token\"],\"scope\":\"openid offline\",\"redirect_uris\":[\"http://localhost:3001/callback-hydra\"],\"post_logout_redirect_uris\":[\"http://localhost:3001/home-hydra\"],\"token_endpoint_auth_method\":\"client_secret_post\"}' -qO- http://hydra:4445/admin/clients || echo '⚠️ Le client existe peut-être déjà ou erreur API.';
      "